name: SaveOnEmpty
main: nl.rgjkuiper.soe.SaveOnEmpty
version: 0.9
description: Saves the server on no players online.
author: Robin Kuiper
commands:
   soe:
      description: The main SaveOnEmpty help